### ISSUE TITLE
Add support for array data types in display output for um-additional-user-columns

### ISSUE THREAD

**Issue by garyvoth** [MissVeronica/um-additional-user-columns#1]
Hello. Is it possible to add support for array datatypes for the um-additional-user-columns plugin?  We have a Yes/No field implemented as a radio control on our backend. When selected for display using the plugin, the output shows 'array' rather than the current value of the field:

![Screenshot 2024-04-23 165721](https://github.com/MissVeronica/um-additional-user-columns/assets/45211745/c10b865d-b9e8-4c3f-9816-cdfc93e5083a)

Thanks for listening.

**Comment by MissVeronica** [comment]
Hello @garyvoth
Yes I have made an addition of imploding arrays with a comma if multiple values now in version 1.2.0.
Download and update the plugin.

**Comment by garyvoth** [comment]
Thank you so much. Works perfectly. 

All the best to you. :-)
